<?php
namespace App\Providers;

use App\Repositories\All\AccidentCategory\AccidentCategoryInterface;
use App\Repositories\All\AccidentCategory\AccidentCategoryRepository;
use App\Repositories\All\AccidentInjuryType\AccidentInjuryTypeInterface;
use App\Repositories\All\AccidentInjuryType\AccidentInjuryTypeRepository;
use App\Repositories\All\AccidentPeople\AccidentPeopleInterface;
use App\Repositories\All\AccidentPeople\AccidentPeopleRepository;
use App\Repositories\All\AccidentRecord\AccidentRecordInterface;
use App\Repositories\All\AccidentRecord\AccidentRecordRepository;
use App\Repositories\All\AccidentType\AccidentTypeInterface;
use App\Repositories\All\AccidentType\AccidentTypeRepository;
use App\Repositories\All\AccidentWitness\AccidentWitnessInterface;
use App\Repositories\All\AccidentWitness\AccidentWitnessRepository;
use App\Repositories\All\AssigneeLevel\AssigneeLevelInterface;
use App\Repositories\All\AssigneeLevel\AssigneeLevelRepository;
use App\Repositories\All\ClinicalSuite\ClinicalSuiteInterface;
use App\Repositories\All\ClinicalSuite\ClinicalSuiteRepository;
use App\Repositories\All\ComAcademicYear\ComAcademicYearInterface;
use App\Repositories\All\ComAcademicYear\ComAcademicYearRepository;
use App\Repositories\All\ComDepartment\DepartmentInterface;
use App\Repositories\All\ComDepartment\DepartmentRepository;
use App\Repositories\All\ComGrades\ComGradesInterface;
use App\Repositories\All\ComGrades\ComGradesRepository;
use App\Repositories\All\ComJobPosition\JobPositionInterface;
use App\Repositories\All\ComJobPosition\JobPositionRepository;
use App\Repositories\All\ComOrganization\ComOrganizationInterface;
use App\Repositories\All\ComOrganization\ComOrganizationRepository;
use App\Repositories\All\ComPermission\ComPermissionInterface;
use App\Repositories\All\ComPermission\ComPermissionRepository;
use App\Repositories\All\ComPersonType\PersonTypeInterface;
use App\Repositories\All\ComPersonType\PersonTypeRepository;
use App\Repositories\All\ComResponsibleSection\ComResponsibleSectionInterface;
use App\Repositories\All\ComResponsibleSection\ComResponsibleSectionRepository;
use App\Repositories\All\ComUserType\UserTypeInterface;
use App\Repositories\All\ComUserType\UserTypeRepository;
use App\Repositories\All\CsConsultingDoctor\ConsultingInterface;
use App\Repositories\All\CsConsultingDoctor\ConsultingRepository;
use App\Repositories\All\CsDesignation\DesignationInterface;
use App\Repositories\All\CsDesignation\DesignationRepository;
use App\Repositories\All\CsMedicineStock\MedicineStockInterface;
use App\Repositories\All\CsMedicineStock\MedicineStockRepository;
use App\Repositories\All\Factory\FactoryInterface;
use App\Repositories\All\Factory\FactoryRepository;
use App\Repositories\All\HazardAndRisk\HazardAndRiskInterface;
use App\Repositories\All\HazardAndRisk\HazardAndRiskRepository;
use App\Repositories\All\HRCategory\HRCategoryInterface;
use App\Repositories\All\HRCategory\HRCategoryRepository;
use App\Repositories\All\HRDivision\HRDivisionInterface;
use App\Repositories\All\HRDivision\HRDivisionRepository;
use App\Repositories\All\HSDocumentDocumentType\DocumentTypeInterface;
use App\Repositories\All\HSDocumentDocumentType\DocumentTypeRepository;
use App\Repositories\All\HSDocumentRecode\DocumentInterface;
use App\Repositories\All\HSDocumentRecode\DocumentRepository;
use App\Repositories\All\HsOcMrMdDocumentType\DocumentTypeInterface as HsOcMrMdDocumentTypeDocumentTypeInterface;
use App\Repositories\All\HsOcMrMdDocumentType\DocumentTypeRepository as HsOcMrMdDocumentTypeDocumentTypeRepository;
use App\Repositories\All\HsOhMrBenefitDocument\BenefitDocumentInterface;
use App\Repositories\All\HsOhMrBenefitDocument\BenefitDocumentRepository;
use App\Repositories\All\HsOhMrBenefitEntitlement\BenefitEntitlementInterface;
use App\Repositories\All\HsOhMrBenefitEntitlement\BenefitEntitlementRepository;
use App\Repositories\All\IncidentCircumstances\IncidentCircumstancesInterface;
use App\Repositories\All\IncidentCircumstances\IncidentCircumstancesRepository;
use App\Repositories\All\IncidentFactors\IncidentFactorsInterface;
use App\Repositories\All\IncidentFactors\IncidentFactorsRepository;
use App\Repositories\All\IncidentPeople\IncidentPeopleInterface;
use App\Repositories\All\IncidentPeople\IncidentPeopleRepository;
use App\Repositories\All\IncidentRecord\IncidentRecodeInterface;
use App\Repositories\All\IncidentRecord\IncidentRecodeRepository;
use App\Repositories\All\IncidentTypeOfConcern\IncidentTypeOfConcernInterface;
use App\Repositories\All\IncidentTypeOfConcern\IncidentTypeOfConcernRepository;
use App\Repositories\All\IncidentTypeOfNearMiss\IncidentTypeOfNearMissInterface;
use App\Repositories\All\IncidentTypeOfNearMiss\IncidentTypeOfNearMissRepository;
use App\Repositories\All\IncidentWitness\IncidentWitnessInterface;
use App\Repositories\All\IncidentWitness\IncidentWitnessRepository;
use App\Repositories\All\MedicineDisposal\MedicineDisposalInterface;
use App\Repositories\All\MedicineDisposal\MedicineDisposalRepository;
use App\Repositories\All\MedicineInventory\MedicineInventoryInterface;
use App\Repositories\All\MedicineInventory\MedicineInventoryRepository;
use App\Repositories\All\MiMedicineNameForm\MedicineFormInterface;
use App\Repositories\All\MiMedicineNameForm\MedicineFormRepository;
use App\Repositories\All\MiMedicineName\MedicineNameInterface;
use App\Repositories\All\MiMedicineName\MedicineNameRepository;
use App\Repositories\All\MiMedicineRequest\MedicineRequestInterface;
use App\Repositories\All\MiMedicineRequest\MedicineRequestRepository;
use App\Repositories\All\MiMedicineType\MedicineTypeInterface;
use App\Repositories\All\MiMedicineType\MedicineTypeRepository;
use App\Repositories\All\OhMiPiSupplierName\SupplierNameInterface;
use App\Repositories\All\OhMiPiSupplierName\SupplierNameRepository;
use App\Repositories\All\OhMiPiSupplierType\SupplierTypeInterface;
use App\Repositories\All\OhMiPiSupplierType\SupplierTypeRepository;
use App\Repositories\All\OhMrBeBenefitType\BenefitTypeInterface;
use App\Repositories\All\OhMrBeBenefitType\BenefitTypeRepository;
use App\Repositories\All\OhMrBenefitRequest\BenefitRequestInterface;
use App\Repositories\All\OhMrBenefitRequest\BenefitRequestRepository;
use App\Repositories\All\SaAiEaActionPlan\EaActionPlanInterface;
use App\Repositories\All\SaAiEaActionPlan\EaActionPlanRepository;
use App\Repositories\All\SaAiEaAuditCategory\ExternalAuditCategoryInterface;
use App\Repositories\All\SaAiEaAuditCategory\ExternalAuditCategoryRepository;
use App\Repositories\All\SaAiEaAuditFirm\ExternalAuditFirmInterface;
use App\Repositories\All\SaAiEaAuditFirm\ExternalAuditFirmRepository;
use App\Repositories\All\SaAiEaAuditStandard\ExternalAuditStandardInterface;
use App\Repositories\All\SaAiEaAuditStandard\ExternalAuditStandardRepository;
use App\Repositories\All\SaAiEaAuditType\ExternalAuditTypeInterface;
use App\Repositories\All\SaAiEaAuditType\ExternalAuditTypeRepository;
use App\Repositories\All\SaAiExternalAudit\ExternalAuditInterface;
use App\Repositories\All\SaAiExternalAudit\ExternalAuditRepository;
use App\Repositories\All\SaAiIaActionPlan\ActionPlanInterface;
use App\Repositories\All\SaAiIaActionPlan\ActionPlanRepository;
use App\Repositories\All\SaAiIaAnswerRecode\AnswerRecodeInterface;
use App\Repositories\All\SaAiIaAnswerRecode\AnswerRecodeRepository;
use App\Repositories\All\SaAiIaAuditTitle\AuditTitleInterface;
use App\Repositories\All\SaAiIaAuditTitle\AuditTitleRepository;
use App\Repositories\All\SaAiIaAuditType\AuditTypeInterface;
use App\Repositories\All\SaAiIaAuditType\AuditTypeRepository;
use App\Repositories\All\SaAiIaContactPerson\ContactPersonInterface;
use App\Repositories\All\SaAiIaContactPerson\ContactPersonRepository;
use App\Repositories\All\SaAiIaInternalAuditee\InternalAuditeeInterface;
use App\Repositories\All\SaAiIaInternalAuditee\InternalAuditeeRepository;
use App\Repositories\All\SaAiIaProcessType\ProcessTypeInterface;
use App\Repositories\All\SaAiIaProcessType\ProcessTypeRepository;
use App\Repositories\All\SaAiIaQrGroupRecode\GroupRecodeInterface;
use App\Repositories\All\SaAiIaQrGroupRecode\GroupRecodeRepository;
use App\Repositories\All\SaAiIaQrQuection\QuestionsInterface;
use App\Repositories\All\SaAiIaQrQuection\QuestionsRepository;
use App\Repositories\All\SaAiIaQuestionRecode\QuestionRecodeInterface;
use App\Repositories\All\SaAiIaQuestionRecode\QuestionRecodeRepository;
use App\Repositories\All\SaAiIaSupplierType\SupplierTypeInterface as SaAiIaSupplierTypeSupplierTypeInterface;
use App\Repositories\All\SaAiIaSupplierType\SupplierTypeRepository as SaAiIaSupplierTypeSupplierTypeRepository;
use App\Repositories\All\SaAiInternalAuditFactory\InternalAuditFactoryInterface;
use App\Repositories\All\SaAiInternalAuditFactory\InternalAuditFactoryRepository;
use App\Repositories\All\SaAiInternalAuditRecode\InternalAuditRecodeInterface;
use App\Repositories\All\SaAiInternalAuditRecode\InternalAuditRecodeRepository;
use App\Repositories\All\SaArEmploymentClassification\ArEmploymentClassificationInterface;
use App\Repositories\All\SaArEmploymentClassification\ArEmploymentClassificationRepository;
use App\Repositories\All\SaArResignationType\ArResignationTypeInterface;
use App\Repositories\All\SaArResignationType\ArResignationTypeRepository;
use App\Repositories\All\SaAttritionRecord\AttritionRecordInterface;
use App\Repositories\All\SaAttritionRecord\AttritionRecordRepository;
use App\Repositories\All\SaCmChemicalManagementRecode\ChemicalManagementRecodeInterface;
use App\Repositories\All\SaCmChemicalManagementRecode\ChemicalManagementRecodeRepository;
use App\Repositories\All\SaCmCmrChemicalFormType\ChemicalFormTypeInterface;
use App\Repositories\All\SaCmCmrChemicalFormType\ChemicalFormTypeRepository;
use App\Repositories\All\SaCmCmrCommercialName\CommercialNameInterface;
use App\Repositories\All\SaCmCmrCommercialName\CommercialNameRepository;
use App\Repositories\All\SaCmCmrHazardType\CmrHazardTypeInterface;
use App\Repositories\All\SaCmCmrHazardType\CmrHazardTypeRepository;
use App\Repositories\All\SaCmCmrProductStandard\ProductStandardInterface;
use App\Repositories\All\SaCmCmrProductStandard\ProductStandardRepository;
use App\Repositories\All\SaCmCmrUseOfPPE\CmrUseOfPPEInterface;
use App\Repositories\All\SaCmCmrUseOfPPE\CmrUseOfPPERepository;
use App\Repositories\All\SaCmCmrZdhcCategory\ZdhcCategoryInterface;
use App\Repositories\All\SaCmCmrZdhcCategory\ZdhcCategoryRepository;
use App\Repositories\All\SaCmPirCertificateRecord\CertificateRecordInterface;
use App\Repositories\All\SaCmPirCertificateRecord\CertificateRecordRepository;
use App\Repositories\All\SaCmPirPositiveList\PositiveListInterface;
use App\Repositories\All\SaCmPirPositiveList\PositiveListRepository;
use App\Repositories\All\SaCmPirSuplierName\SuplierNameInterface;
use App\Repositories\All\SaCmPirSuplierName\SuplierNameRepository;
use App\Repositories\All\SaCmPirTestingLab\TestingLabInterface;
use App\Repositories\All\SaCmPirTestingLab\TestingLabRepository;
use App\Repositories\All\SaCmPurchaseInventory\PurchaseInventoryInterface;
use App\Repositories\All\SaCmPurchaseInventory\PurchaseInventoryRepository;
use App\Repositories\All\SaEEmrAcCategory\ConsumptionCategoryInterface;
use App\Repositories\All\SaEEmrAcCategory\ConsumptionCategoryRepository;
use App\Repositories\All\SaEmrAddConcumption\AddConcumptionInterface;
use App\Repositories\All\SaEmrAddConcumption\AddConcumptionRepository;
use App\Repositories\All\SaEnvirementManagementRecode\EnvirementManagementRecodeInterface;
use App\Repositories\All\SaEnvirementManagementRecode\EnvirementManagementRecodeRepository;
use App\Repositories\All\SaETargetSetting\TargetSettingRecodeInterface;
use App\Repositories\All\SaETargetSetting\TargetSettingRecodeRepository;
use App\Repositories\All\SaETsCategory\TsCategoryInterface;
use App\Repositories\All\SaETsCategory\TsCategoryRepository;
use App\Repositories\All\SaETsSource\TsSourceInterface;
use App\Repositories\All\SaETsSource\TsSourceRepository;
use App\Repositories\All\SaGrCategory\GrCategoryInterface;
use App\Repositories\All\SaGrCategory\GrCategoryRepository;
use App\Repositories\All\SaGrChannel\GrChannelInterface;
use App\Repositories\All\SaGrChannel\GrChannelRepository;
use App\Repositories\All\SaGrCommiteeMemberDetails\GrCommiteeMemberDetailsInterface;
use App\Repositories\All\SaGrCommiteeMemberDetails\GrCommiteeMemberDetailsRepository;
use App\Repositories\All\SaGrievanceRecord\GrievanceInterface;
use App\Repositories\All\SaGrievanceRecord\GrievanceRepository;
use App\Repositories\All\SaGrLegalAdvisorDetails\GrLegalAdvisorDetailsInterface;
use App\Repositories\All\SaGrLegalAdvisorDetails\GrLegalAdvisorDetailsRepository;
use App\Repositories\All\SaGrNomineeDetails\GrNomineeDetailsInterface;
use App\Repositories\All\SaGrNomineeDetails\GrNomineeDetailsRepository;
use App\Repositories\All\SaGrRespondentDetails\GrRespondentDetailsInterface;
use App\Repositories\All\SaGrRespondentDetails\GrRespondentDetailsRepository;
use App\Repositories\All\SaGrSubmissions\GrSubmissionsInterface;
use App\Repositories\All\SaGrSubmissions\GrSubmissionsRepository;
use App\Repositories\All\SaGrTopic\GrTopicInterface;
use App\Repositories\All\SaGrTopic\GrTopicRepository;
use App\Repositories\All\SaRagRecode\RagRecodeInterface;
use App\Repositories\All\SaRagRecode\RagRecodeRepository;
use App\Repositories\All\SaRrCategory\RrCategoryInterface;
use App\Repositories\All\SaRrCategory\RrCategoryRepository;
use App\Repositories\All\SaRrCountryName\RrCountryNameInterface;
use App\Repositories\All\SaRrCountryName\RrCountryNameRepository;
use App\Repositories\All\SaRrDesignationName\RrDesignationNameInterface;
use App\Repositories\All\SaRrDesignationName\RrDesignationNameRepository;
use App\Repositories\All\SaRrEmployeeType\RrEmployeeTypeInterface;
use App\Repositories\All\SaRrEmployeeType\RrEmployeeTypeRepository;
use App\Repositories\All\SaRrEmploymentType\RrEmploymentTypeInterface;
use App\Repositories\All\SaRrEmploymentType\RrEmploymentTypeRepository;
use App\Repositories\All\SaRrFunction\RrFunctionInterface;
use App\Repositories\All\SaRrFunction\RrFunctionRepository;
use App\Repositories\All\SaRrSourceOfHiring\RrSourceOfHiringInterface;
use App\Repositories\All\SaRrSourceOfHiring\RrSourceOfHiringRepository;
use App\Repositories\All\SaRrState\RrStateInterface;
use App\Repositories\All\SaRrState\RrStateRepository;
use App\Repositories\All\SaSDGRecode\SDGRecodeInterface;
use App\Repositories\All\SaSDGRecode\SDGRecodeRepository;
use App\Repositories\All\SaSrAdditionalSDG\AdditionalSDGInterface;
use App\Repositories\All\SaSrAdditionalSDG\AdditionalSDGRepository;
use App\Repositories\All\SaSrAlignmentSDG\AlignmentSDGInterface;
use App\Repositories\All\SaSrAlignmentSDG\AlignmentSDGRepository;
use App\Repositories\All\SaSrImpactDetails\ImpactDetailsInterface;
use App\Repositories\All\SaSrImpactDetails\ImpactDetailsRepository;
use App\Repositories\All\SaSrImpactType\ImpactTypeInterface;
use App\Repositories\All\SaSrImpactType\ImpactTypeRepository;
use App\Repositories\All\SaSrMaterialityIssues\MaterialityIssuesInterface;
use App\Repositories\All\SaSrMaterialityIssues\MaterialityIssuesRepository;
use App\Repositories\All\SaSrMaterialityType\MaterialityTypeInterface;
use App\Repositories\All\SaSrMaterialityType\MaterialityTypeRepository;
use App\Repositories\All\SaSrPillars\PillarsInterface;
use App\Repositories\All\SaSrPillars\PillarsRepository;
use App\Repositories\All\SaSrSDG\SrSdgInterface;
use App\Repositories\All\SaSrSDG\SrSdgRepository;
use App\Repositories\All\User\UserInterface;
use App\Repositories\All\User\UserRepository;
use Illuminate\Support\Facades\Vite;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        Vite::prefetch(concurrency: 3);


        $this->app->bind(DepartmentInterface::class, DepartmentRepository::class);
        $this->app->bind(FactoryInterface::class, FactoryRepository::class);
        $this->app->bind(UserInterface::class, UserRepository::class);
        $this->app->bind(JobPositionInterface::class, JobPositionRepository::class);
        $this->app->bind(UserTypeInterface::class, UserTypeRepository::class);
        $this->app->bind(AssigneeLevelInterface::class, AssigneeLevelRepository::class);
        $this->app->bind(HRCategoryInterface::class, HRCategoryRepository::class);
        $this->app->bind(HRDivisionInterface::class, HRDivisionRepository::class);
        $this->app->bind(ComResponsibleSectionInterface::class, ComResponsibleSectionRepository::class);
        $this->app->bind(PersonTypeInterface::class, PersonTypeRepository::class);
        $this->app->bind(ComPermissionInterface::class, ComPermissionRepository::class);
         $this->app->bind(ClinicalSuiteInterface::class, ClinicalSuiteRepository::class);
        $this->app->bind(DesignationInterface::class, DesignationRepository::class);
        $this->app->bind(ConsultingInterface::class, ConsultingRepository::class);
        $this->app->bind(MedicineStockInterface::class, MedicineStockRepository::class);

        $this->app->bind(ChemicalManagementRecodeInterface::class, ChemicalManagementRecodeRepository::class);
        $this->app->bind(CommercialNameInterface::class, CommercialNameRepository::class);
        $this->app->bind(ChemicalFormTypeInterface::class, ChemicalFormTypeRepository::class);
        $this->app->bind(ZdhcCategoryInterface::class, ZdhcCategoryRepository::class);
        $this->app->bind(ProductStandardInterface::class, ProductStandardRepository::class);
        $this->app->bind(CmrHazardTypeInterface::class, CmrHazardTypeRepository::class);
        $this->app->bind(CmrUseOfPPEInterface::class, CmrUseOfPPERepository::class);
        $this->app->bind(PurchaseInventoryInterface::class, PurchaseInventoryRepository::class);
        $this->app->bind(CertificateRecordInterface::class, CertificateRecordRepository::class);
        $this->app->bind(TestingLabInterface::class, TestingLabRepository::class);
        $this->app->bind(PositiveListInterface::class, PositiveListRepository::class);
        $this->app->bind(SuplierNameInterface::class, SuplierNameRepository::class);
        $this->app->bind(ComOrganizationInterface::class, ComOrganizationRepository::class);
        $this->app->bind(SupplierTypeInterface::class, SupplierTypeRepository::class);

        $this->app->bind(ComGradesInterface::class, ComGradesRepository::class);
        $this->app->bind(ComAcademicYearInterface::class, ComAcademicYearRepository::class);

    }
}
